/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.shoeStore.component;

import com.shoeStore.model.Shoe;
import com.shoeStore.service.ShoeService;
import java.awt.Cursor;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class CpnItem extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public CpnItem() {
        initComponents();
//        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    private Shoe shoe;
    private ShoeService shoeService;
    public void  setData(Shoe shoe) {
        this.shoe = shoe;
        shoeService = new ShoeService();
        itemName.setText(shoe.getName());
        itemTitle.setText(shoe.getTitle());
        ImageIcon imageIcon = shoeService.fitSize(shoe, itemPic);
        itemPic.setIcon(imageIcon);
        DecimalFormat df = new DecimalFormat("$#,##0.00");
        itemPrice.setText(df.format(shoe.getPrice()));

        // lấy ra tên của cate thông qua cateID
        String cateName = shoeService.getCateFromProduct(shoe);
        itemCate.setText(cateName);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemName = new javax.swing.JLabel();
        itemTitle = new javax.swing.JLabel();
        pic = new javax.swing.JPanel();
        itemPic = new javax.swing.JLabel();
        itemCate = new javax.swing.JLabel();
        itemPrice = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 250));

        itemName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        itemName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemName.setText("Item name");

        itemTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        itemTitle.setForeground(new java.awt.Color(178, 178, 178));
        itemTitle.setText("Mô tả");
        itemTitle.setAutoscrolls(true);

        pic.setLayout(null);

        itemPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoeStore/image/shoe.png"))); // NOI18N
        itemPic.setPreferredSize(new java.awt.Dimension(200, 150));
        pic.add(itemPic);
        itemPic.setBounds(0, 0, 190, 140);

        itemCate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        itemCate.setText("Nhãn hiệu");

        itemPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        itemPrice.setText("0.0 VNĐ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(itemCate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemPrice)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCate)
                    .addComponent(itemPrice))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemCate;
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel itemPic;
    private javax.swing.JLabel itemPrice;
    private javax.swing.JLabel itemTitle;
    private javax.swing.JPanel pic;
    // End of variables declaration//GEN-END:variables
}
